name: AQI Alert Checker and CSV logger

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "AIRVISUAL_API_KEY=${{ secrets.AIRVISUAL_API_KEY }}" >> $GITHUB_ENV
          echo "PUSHBULLET_API_KEY=${{ secrets.PUSHBULLET_API_KEY }}" >> $GITHUB_ENV

      - name: Run script
        run: python script.py

      - name: Set Git user info
        run: |
          git config user.name 'marcel-gaida'
          git config user.email 'marcel.gaida@fu-berlin.de'

      - name: Fetch and merge changes
        run: |
          git fetch
          git merge origin/main --allow-unrelated-histories

      - name: Commit changes
        run: |
          git add data.csv
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update data.csv"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
